### ISSUE TITLE
Todo App 요구사항 명세서

### ISSUE THREAD

**Issue by ciaomin** [ciaomin/Dadaicksun_pre_38#1]
### 만들고자 하는 기능이 무엇인가요?
ex) Todo 생성 기능

### Create
 * [ ] 할 일 목록 등록

### Read
 * [ ] 등록된 할 일 목록 전체 조회
 * [ ] 등록된 할 일 단건 조회

### Update
* [ ] 이미 한 일에 완료 표시
* [ ] 할 일 내용 수정

### Delete
* [ ] 등록된 전체 할 일 삭제
* [ ] 등록된 할 일 단건 삭제

### POST

| method | end point | request | response |
|-----|----|--------|----------|
|POST|http://localhost:8080|{</br>"title" : "study", </br>"completed" : false</br>}|[{location : URL, httpstatus : 201}]|
|GET|http://localhost:8080||[</br>{</br>"id" : 1, </br>"title" : "study", </br>"completed" : false</br>},</br>{</br>"id" : 2, </br>"title" : "java", </br>"completed" : false</br>}</br>...</br>{</br>httpstatus : 200</br>}</br>]|
|GET|http://localhost:8080/{id}||[</br>{</br>"id" : 1, </br>"title" : "study", </br>"completed" : false</br>},</br>{</br>httpstatus : 200</br>}</br>]|
|PATCH|localhost:8080/{id}|{</br>"title" : "study", </br>"completed" : false</br>}|{</br>"id" : 1, </br>"title" : "study", </br>"completed" : false</br>}, </br>{</br>httpstatus : 200</br>}|
|DELETE|localhost:8080|||||
|DELETE|localhost:8080/{id}||||
